### ISSUE TITLE
footbot_gripping example not working properly with ARGoS version 3.0.0-beta40

### ISSUE THREAD

**Issue by alanmillard** [ilpincy/argos3-examples#1]
The `footbot_gripping` example no longer works properly. The physics simulation seems to be out of sync with the visualisation - the robot does not appear to move, but the cylinder still moves as if being gripped and pulled by an invisible robot.

The example code works with ARGoS version 3.0.0-beta39, but not with 3.0.0-beta40.

**Comment by ilpincy** [comment]
Hi Alan,

Thanks for the bug report! I will look into it ASAP.

Cheers,
Carlo

On Thu, Apr 14, 2016 at 2:58 PM, Alan Millard <notifications@github.com>
wrote:

> The footbot_gripping example no longer works properly. The physics
> simulation seems to be out of sync with the visualisation - the robot does
> not appear to move, but the cylinder still moves as if being gripped and
> pulled by an invisible robot.
>
> The example code works with ARGoS version 3.0.0-beta39, but not with
> 3.0.0-beta40.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ilpincy/argos3-examples/issues/1>
>



-- 
Carlo Pinciroli, Ph.D.
http://carlo.pinciroli.net/

**Comment by Waqar731** [comment]
Hi Alan,
You are facing the same problem as i had. Actually i have done my BS(CS) project in ARGoS simulator in july 2015. Now in first week of april 2016, when i trying to run then my robot was not working also. So i spend 4 hours on it, then i conclude according to 40th version of ARGos you must embed proximity sensor on foot-bot (doesn't matter you use it or not). Now i did with gripping example. So now robot is moving.

1)  Include proximity sensor in .argos file in sensor tag
2)  Include header file in .h file and also create a pointer
3)  Make constructor in .cpp file.

You will see robot will move in girpping example.

Waqar Hussain
Pakistan

**Comment by EMerckx** [comment]
Hello,

I had the same issue and with the comment of @Waqar731, I've been able to fix it. But I've only added the proximity sensor to the footbot controller in the .argos configuration file, nothing more.

    <sensors>
        <footbot_proximity implementation="default" show_rays="true" />
    </sensors>

Sincerely yours,
Ewout Merckx.

**Comment by alanmillard** [comment]
@EMerckx: simply adding the proximity sensor to the footbot controller in the .argos configuration file also works for me! How strange...

Hopefully this makes sense to @ilpincy :)

**Comment by ilpincy** [comment]
Thanks for the suggestions! I does not make much sense to me, but I'll have
a look at the problem today and will try to understand what is going on.

On Tue, Apr 19, 2016 at 9:40 AM, Alan Millard <notifications@github.com>
wrote:

> @EMerckx <https://github.com/EMerckx>: simply adding the proximity sensor
> to the footbot controller in the .argos configuration file also works for
> me! How strange...
>
> Hopefully this makes sense to @ilpincy <https://github.com/ilpincy> :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ilpincy/argos3-examples/issues/1#issuecomment-211926570>
>



-- 
Carlo Pinciroli, Ph.D.
http://carlo.pinciroli.net/

**Comment by ilpincy** [comment]
I fixed the problem. It was a bug in ARGoS that I introduced in beta40 (the RAB entity, if unused, was disabling also the origin anchor, which was preventing the drawing from working correctly). Thanks everybody for the feedback! The fix is released in the new beta41.
