### ISSUE TITLE
 Can't load library "/usr/lib/argos3/libargos3plugin_simulator_epuck.so"

### ISSUE THREAD

**Issue by rookie-cyber** [ilpincy/argos3-examples#12]
Hi! 
I take the liberty of asking you a simple question. I tried to followed the guide you wrote and compiled without errors, but when I executed the example, I got the following error:
~/argos3-examples$ argos3 -c experiments/diffusion_1.argos
[INFO] Loaded library "/usr/lib/argos3/libargos3core_simulator.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics2d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_entities.so"
[FATAL] Can't load library "/usr/lib/argos3/libargos3plugin_simulator_epuck.so" after trying the following:

  /usr/lib/argos3/libargos3plugin_simulator_epuck.so: libQt5Core.so.5: cannot open shared object file: No such file or directory

  /usr/lib/argos3/libargos3plugin_simulator_epuck.so.so: /usr/lib/argos3/libargos3plugin_simulator_epuck.so.so: cannot open shared object file: No such file or directory

  /usr/lib/argos3/libargos3plugin_simulator_epuck.so.so: /usr/lib/argos3/libargos3plugin_simulator_epuck.so.so: cannot open shared object file: No such file or directory
Has this happened to you before?

**Comment by ilpincy** [comment]
This is not a bug with the examples, so I'd prefer if you checked the [ARGoS forum](https://www.argos-sim.info/forum/).
