### ISSUE TITLE
Question! ZigBee

### ISSUE THREAD

**Issue by laeeg93** [ilpincy/argos3-examples#4]
Hi Mr Pincy
I´m student from México and I´m trying to work on ARGoS, but I have a question.
On ARGoS, you don't have a controller or a lib to work with ZigBee or something similar, to comunicate the robots wirelessly?

I really appreciate your time and I'm really fascinated with ARGoS.

**Comment by ilpincy** [comment]
Please don't write questions here. This page is only for issue tracking about examples. Write on the forum instead.
