### ISSUE TITLE
Segmentation fault (core dumped) during getting Robot Id on terminal

### ISSUE THREAD

**Issue by Waqar731** [ilpincy/argos3-examples#7]
Hi,
I am trying to get the foot-bot id on terminal. I tried it with the following code:

1.  First of all, in my header file of controller, I write the header file like this:
`#include <argos3/plugins/robots/foot-bot/simulator/footbot_entity.h>`

2.  After header declaration, I make a pointer to that class in same header file like this:
`CFootBotEntity* c_entity;`

3.  After making pointer, I writing the following code in my (.cpp) file of controller:
```
const std::string str_id = c_entity->GetId().c_str();
std::cout << "Robot ID :  " << str_id << "\n";
```

4.  After above code, I compile the files using 'make', and it successfully compiled.
5.  After compiling, when I tried to run the simulation then I got the following error.
`Segmentation fault (core dumped)`

> **Where am I wrong in the code? Please help me in this issue.**

Thanks

**Comment by SnowCarter** [comment]
I meet the same issue. I think it might be a problem...
![image](https://user-images.githubusercontent.com/33834347/76022681-964f4f80-5ef5-11ea-9a44-e032f21afe84.png)

**Comment by ilpincy** [comment]
It's impossible to know without seeing your code. The original post was an obvious bug in their code.

**Comment by SnowCarter** [comment]
Thank you very for your reply. After reinstalling all buzz and argos3,  it works well now.
