### ISSUE TITLE
Flocking example

### ISSUE THREAD

**Issue by AshwinRaviraj** [ilpincy/argos3-examples#9]
When I reset the flocking experiment the agents/robots doesn’t try to arrogate they just to go towards the light source… I can’t seem to fix this issue?

Best 
Ashwin

**Comment by ilpincy** [comment]
Thanks for spotting the issue! The camera was not enabled after reset.

**Comment by AshwinRaviraj** [comment]
Anytime, so to make it work should I just add the following in the reset function?  m_pcCamera->Enable();

**Comment by ilpincy** [comment]
Check the last commit I made, which fixes the issue. You need to enable the camera and switch the leds on. Just git pull the latest version and it'll work.
